comma:=,
MAKEVARS:=.makevars

define BUILD_d_file
.%.d: %.$(1) $(MAKEVARS)/$(2) $(MAKEVARS)/CPPFLAGS $(MAKEVARS)/$(2)FLAGS
	@set -e; trap 'rm -f $@.$$$$' EXIT; rm -f $@; \
	 $($(2)) -MM $(CPPFLAGS) $($(2)FLAGS) $< > $@.$$$$; \
	 sed 's,\($(notdir $*)\)\.o[ :]*,$*.o $@ : ,g' < $@.$$$$ > $@
endef

$(call BUILD_d_file,cc,CXX)
$(call BUILD_d_file,cpp,CXX)
$(call BUILD_d_file,C,CXX)
$(call BUILD_d_file,c,CC)
$(call BUILD_d_file,S,AS)

$(MAKEVARS):
	@mkdir -p $@

$(MAKEVARS)/%.tmp: $(MAKEVARS) FORCE
	@echo $(call $*) > $@

$(MAKEVARS)/%: $(MAKEVARS)/%.tmp
	@cmp -s $< $@ || cp -f $< $@
	@rm $<

.PHONY: FORCE
.PRECIOUS: $(MAKEVARS)/%
