comma:=,
MAKEVARS:=.makevars

.%.d: %.cc $(MAKEVARS)/CXX $(MAKEVARS)/CPPFLAGS $(MAKEVARS)/CXXFLAGS
	@set -e; trap 'rm -f $@.$$$$' EXIT; rm -f $@; \
	 $(CXX) -MM $(CPPFLAGS) $(CXXFLAGS) $< > $@.$$$$; \
	 sed 's,\($(notdir $*)\)\.o[ :]*,$*.o $@ : ,g' < $@.$$$$ > $@

.%.d: %.cpp $(MAKEVARS)/CXX $(MAKEVARS)/CPPFLAGS $(MAKEVARS)/CXXFLAGS
	@set -e; trap 'rm -f $@.$$$$' EXIT; rm -f $@; \
	 $(CXX) -MM $(CPPFLAGS) $(CXXFLAGS) $< > $@.$$$$; \
	 sed 's,\($(notdir $*)\)\.o[ :]*,$*.o $@ : ,g' < $@.$$$$ > $@

.%.d: %.C $(MAKEVARS)/CXX $(MAKEVARS)/CPPFLAGS $(MAKEVARS)/CXXFLAGS
	@set -e; trap 'rm -f $@.$$$$' EXIT; rm -f $@; \
	 $(CXX) -MM $(CPPFLAGS) $(CXXFLAGS) $< > $@.$$$$; \
	 sed 's,\($(notdir $*)\)\.o[ :]*,$*.o $@ : ,g' < $@.$$$$ > $@

.%.d: %.c $(MAKEVARS)/CC $(MAKEVARS)/CPPFLAGS $(MAKEVARS)/CFLAGS
	@set -e; trap 'rm -f $@.$$$$' EXIT; rm -f $@; \
	 $(CC) -MM $(CPPFLAGS) $(CFLAGS) $< > $@.$$$$; \
	 sed 's,\($(notdir $*)\)\.o[ :]*,$*.o $@ : ,g' < $@.$$$$ > $@

.%.d: %.S $(MAKEVARS)/AS $(MAKEVARS)/ASFLAGS
	@set -e; trap 'rm -f $@.$$$$' EXIT; rm -f $@; \
	 $(AS) -MM $(ASFLAGS) $< > $@.$$$$; \
	 sed 's,\($(notdir $*)\)\.o[ :]*,$*.o $@ : ,g' < $@.$$$$ > $@

$(MAKEVARS):
	@mkdir -p $@

$(MAKEVARS)/%.tmp: $(MAKEVARS) FORCE
	@echo $(call $*) > $@

$(MAKEVARS)/%: $(MAKEVARS)/%.tmp
	@cmp -s $< $@ || cp -f $< $@
	@rm $<

.PHONY: FORCE
.PRECIOUS: $(MAKEVARS)/%
